
--Standard Modules
local awful = require("awful")
local gears = require("gears")
local wibox = require("wibox")
local beautiful = require("beautiful")
local dpi = beautiful.xresources.apply_dpi

--Colors
local color = require("layout.dock.color")
local icon_path = require("layout.dock.icon_path")

--Main Widget
local button = wibox.widget {
    {
        {
            widget = wibox.widget.imagebox,
            image = os.getenv("HOME") .. icon_path .. "Spotify.png",
            resize = true,
            opacity = 1,
        },
        left   = dpi(3),
        right  = dpi(3),
        top    = dpi(3),
        bottom = dpi(3),
        widget = wibox.container.margin
    },
    shape = function(cr, width, height)
        -- gears.shape.rounded_rect(cr, width, height, 8)
        gears.shape.rounded_rect(cr, width, height, 8)
      end,
    -- bg = color.background_dark,
    widget = wibox.container.background,
    forced_height = dpi(30),
    forced_width = dpi(30),
}

--Open app on click
button:connect_signal("button::press", function(_, _, _, button)
    if button == 1 then
        awful.spawn.with_shell("spotify")
    end
end)


-- Hover highlight effects
button:connect_signal("mouse::enter", function()
    button.bg = color.background_lighter
end)

button:connect_signal("mouse::leave", function()
    button.bg = color.background_dark
end)

button:connect_signal("button::press", function()
    button.bg = color.background_morelight
end)

button:connect_signal("button::release", function()
    button.bg = color.background_dark
end)


return button

---
--- Generated by Luanalysis
--- Created by laurinha.
--- DateTime: 9/8/23 6:52 PM
---
